### PR TITLE
Fix Directory.json according to new sort 

### PR DESCRIPTION
**Pull request by samarjeet27**
See https://github.com/fossasia/fossasia-communities/pull/65
Sorted according to countries

### CODE REVIEW

**Comment by RoonyH** [comment]
I can't see an entry for LinuxBahrain but you add it in https://github.com/fossasia/fossasia-communities/pull/65?

**Comment by samarjeet27** [comment]
@RoonyH https://github.com/fossasia/directory.api.fossasia.net/blob/master/directory.json#L8 a duplicate it already exists

**Comment by RoonyH** [comment]
ah. That seems to link to that students' github account though. I guess we need it to link to fossasia's repo?

**Comment by samarjeet27** [comment]
@RoonyH OK, changed that

**Pull request merged**
