### PR TITLE
Added Sri Lanka Raw Link

### PR DESCRIPTION
**Pull request by JamMurz**
Added Mozilla Sri Lanka raw link to the file

### CODE REVIEW

**Comment by samarjeet27** [comment]
Hi,@JamMurz your link is dead

**Comment by JamMurz** [comment]
@samarjeet27  Sorry, I claimed my task but it hasn't been approved yet so the link is dead at the moment.

**Comment by samarjeet27** [comment]
@JamMurz, will merge once your task has been approved by mentors. Btw try adding some feeds and timeline information :)

**Comment by ty221** [comment]
https://github.com/fossasia/fossasia-communities/pull/62

Please also @JamMurz  take a look on my notices :D

**Comment by JamMurz** [comment]
@samarjeet27 The raw link is now working. I also added RSS. Thanks :D

**Comment by samarjeet27** [comment]
Merged https://github.com/fossasia/directory.api.fossasia.net/commit/571ec0c37a84449fad83324f45a78706aea2d2e3

Thanks !

**Pull request closed without merging**
